**IMPORT DEPENDENCIES**

In [1]:
import pandas as pd
from sqlalchemy import create_engine

pd.set_option("display.max_columns", None)

**LOAD DATA**

In [2]:
df = pd.read_csv(
    "../data/cleaned/supply_chain_features.csv",
    parse_dates=["OrderDate", "ShippingDate"]
)


df.head()

,OrderType,ActualShippingDays,ScheduledShippingDays,Profit,DeliveryStatus,LateDeliveryRisk,CategoryID,CategoryName,CustomerCity,CustomerCountry,CustomerFirstName,CustomerID,CustomerLastName,CustomerSegment,CustomerState,CustomerStreet,DepartmentID,DepartmentName,Latitude,Longitude,Market,OrderCity,OrderCountry,OrderDate,OrderID,DiscountAmount,DiscountRate,OrderItemID,ProfitRatio,Quantity,GrossSales,NetSales,OrderRegion,OrderState,OrderStatus,ProductID,ProductImage,ProductName,ProductPrice,ShippingDate,ShippingMode,OrderYear,OrderQuarter,OrderMonthNumber,OrderMonth,OrderDay,IsWeekend,ShippingDelay,IsLateDelivery,DeliveryPerformance,ProfitMarginPercent,ProfitCategory,OrderValueCategory,HasDiscount,DiscountCategory,ShippingSpeed
0,DEBIT,3,4,91.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,2018-01-31 22:56:00,77202,13.110000,0.04,180517,0.29,1,327.75,314.640015,Southeast Asia,Java Occidental,COMPLETE,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-02-03 22:56:00,Standard Class,2018,1,1,January,Wednesday,False,-1,No,Early,27.841342,Low Profit,Premium,Yes,Low,Standard
1,TRANSFER,5,4,-249.089996,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,2018-01-13 12:27:00,75939,16.389999,0.05,179254,-0.80,1,327.75,311.359985,South Asia,Rajastán,PENDING,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-18 12:27:00,Standard Class,2018,1,1,January,Saturday,True,1,Yes,Late,-75.999999,Loss,Premium,Yes,Low,Slow
2,CASH,4,4,-247.779999,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,2018-01-13 12:06:00,75938,18.030001,0.06,179253,-0.80,1,327.75,309.720001,South Asia,Rajastán,CLOSED,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-17 12:06:00,Standard Class,2018,1,1,January,Saturday,True,0,No,On Time,-75.600305,Loss,Premium,Yes,Low,Standard
3,DEBIT,3,4,22.860001,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,2018-01-13 11:45:00,75937,22.940001,0.07,179252,0.08,1,327.75,304.809998,Oceania,Queensland,COMPLETE,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-16 11:45:00,Standard Class,2018,1,1,January,Saturday,True,-1,No,Early,6.974829,Low Profit,Premium,Yes,Low,Standard
4,PAYMENT,2,4,134.210007,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,2018-01-13 11:24:00,75936,29.500000,0.09,179251,0.45,1,327.75,298.250000,Oceania,Queensland,PENDING_PAYMENT,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-15 11:24:00,Standard Class,2018,1,1,January,Saturday,True,-2,No,Early,40.948896,Medium Profit,Premium,Yes,Low,Fast

In [3]:
df.shape

(180519, 56)

**CONNECT TO SQL SERVER**

In [6]:
pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\dell\appdata\roaming\python\python313\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
username = "root"
password = "Akhil1978"
host = "localhost"
port = "3306"
database = "SupplyChainAnalytics"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [18]:
engine

Engine(mysql+pymysql://root:***@localhost:3306/SupplyChainAnalytics)

**CREATE DIMENTION TABLE FOR CUSTOMER**

In [19]:
dim_customer = (df[["CustomerID",
                    "CustomerFirstName",
                    "CustomerLastName",
                    "CustomerSegment",
                    "CustomerCity",
                    "CustomerState",
                    "CustomerCountry"]].drop_duplicates().sort_values("CustomerID"))

dim_customer.head()

,CustomerID,CustomerFirstName,CustomerLastName,CustomerSegment,CustomerCity,CustomerState,CustomerCountry
9138,1,Richard,Hernandez,Consumer,Brownsville,TX,EE. UU.
9111,2,Mary,Barrett,Consumer,Littleton,CO,EE. UU.
20916,3,Ann,Smith,Consumer,Caguas,PR,Puerto Rico
9208,4,Mary,Jones,Consumer,San Marcos,CA,EE. UU.
6717,5,Robert,Hudson,Home Office,Caguas,PR,Puerto Rico

In [20]:
dim_customer.shape

(20652, 7)

**LOAD CUSTOMER DATA INTO SQL(dimcustomer)**

In [24]:
dim_customer.to_sql(
    "dimcustomer",
    con=engine,
    if_exists="append",
    index=False
)

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1' for key 'dimcustomer.PRIMARY'")
[SQL: INSERT INTO dimcustomer (`CustomerID`, `CustomerFirstName`, `CustomerLastName`, `CustomerSegment`, `CustomerCity`, `CustomerState`, `CustomerCountry`) VALUES (%(CustomerID)s, %(CustomerFirstName)s, %(CustomerLastName)s, %(CustomerSegment)s, %(CustomerCity)s, %(CustomerState)s, %(CustomerCountry)s)]
[parameters: [{'CustomerID': 1, 'CustomerFirstName': 'Richard', 'CustomerLastName': 'Hernandez', 'CustomerSegment': 'Consumer', 'CustomerCity': 'Brownsville', 'CustomerState': 'TX', 'CustomerCountry': 'EE. UU.'}, {'CustomerID': 2, 'CustomerFirstName': 'Mary', 'CustomerLastName': 'Barrett', 'CustomerSegment': 'Consumer', 'CustomerCity': 'Littleton', 'CustomerState': 'CO', 'CustomerCountry': 'EE. UU.'}, {'CustomerID': 3, 'CustomerFirstName': 'Ann', 'CustomerLastName': 'Smith', 'CustomerSegment': 'Consumer', 'CustomerCity': 'Caguas', 'CustomerState': 'PR', 'CustomerCountry': 'Puerto Rico'}, {'CustomerID': 4, 'CustomerFirstName': 'Mary', 'CustomerLastName': 'Jones', 'CustomerSegment': 'Consumer', 'CustomerCity': 'San Marcos', 'CustomerState': 'CA', 'CustomerCountry': 'EE. UU.'}, {'CustomerID': 5, 'CustomerFirstName': 'Robert', 'CustomerLastName': 'Hudson', 'CustomerSegment': 'Home Office', 'CustomerCity': 'Caguas', 'CustomerState': 'PR', 'CustomerCountry': 'Puerto Rico'}, {'CustomerID': 6, 'CustomerFirstName': 'Mary', 'CustomerLastName': 'Smith', 'CustomerSegment': 'Consumer', 'CustomerCity': 'Passaic', 'CustomerState': 'NJ', 'CustomerCountry': 'EE. UU.'}, {'CustomerID': 7, 'CustomerFirstName': 'Melissa', 'CustomerLastName': 'Wilcox', 'CustomerSegment': 'Corporate', 'CustomerCity': 'Caguas', 'CustomerState': 'PR', 'CustomerCountry': 'Puerto Rico'}, {'CustomerID': 8, 'CustomerFirstName': 'Megan', 'CustomerLastName': 'Smith', 'CustomerSegment': 'Corporate', 'CustomerCity': 'Lawrence', 'CustomerState': 'MA', 'CustomerCountry': 'EE. UU.'}  ... displaying 10 of 20652 total bound parameter sets ...  {'CustomerID': 20756, 'CustomerFirstName': 'Cherokee', 'CustomerLastName': 'Callahan', 'CustomerSegment': 'Corporate', 'CustomerCity': 'Berwyn', 'CustomerState': 'IL', 'CustomerCountry': 'EE. UU.'}, {'CustomerID': 20757, 'CustomerFirstName': 'Katelyn', 'CustomerLastName': 'Gonzales', 'CustomerSegment': 'Corporate', 'CustomerCity': 'Miami', 'CustomerState': 'FL', 'CustomerCountry': 'EE. UU.'}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

**CREATE DIMENTION TABLE FOR CATEGORY**

In [25]:
dim_category = (
    df[
        [
            "CategoryID",
            "CategoryName"
        ]
    ]
    .drop_duplicates()
    .sort_values("CategoryID")
)

dim_category.head()

     CategoryID         CategoryName
175           2               Soccer
119           3  Baseball & Softball
174           4           Basketball
775           5             Lacrosse
294           6     Tennis & Racquet

In [26]:
dim_category.shape

(51, 2)

**LOAD CATOGERY DATA INTO SQL(dimcategory)**

In [28]:
dim_category.to_sql(
    "dimcategory",
    con=engine,
    if_exists="append",
    index=False
)

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '2' for key 'dimcategory.PRIMARY'")
[SQL: INSERT INTO dimcategory (`CategoryID`, `CategoryName`) VALUES (%(CategoryID)s, %(CategoryName)s)]
[parameters: [{'CategoryID': 2, 'CategoryName': 'Soccer'}, {'CategoryID': 3, 'CategoryName': 'Baseball & Softball'}, {'CategoryID': 4, 'CategoryName': 'Basketball'}, {'CategoryID': 5, 'CategoryName': 'Lacrosse'}, {'CategoryID': 6, 'CategoryName': 'Tennis & Racquet'}, {'CategoryID': 7, 'CategoryName': 'Hockey'}, {'CategoryID': 9, 'CategoryName': 'Cardio Equipment'}, {'CategoryID': 10, 'CategoryName': 'Strength Training'}  ... displaying 10 of 51 total bound parameter sets ...  {'CategoryID': 75, 'CategoryName': 'Video Games'}, {'CategoryID': 76, 'CategoryName': "Women's Clothing"}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

**CREATE DIMENTION TABLE FOR PRODUCT**

In [29]:
dim_product = (
    df[
        [
            "ProductID",
            "ProductName",
            "ProductPrice",
            "DepartmentID",
            "DepartmentName",
            "CategoryID",
            "ProductImage"
        ]
    ]
    .drop_duplicates()
    .sort_values("ProductID")
)

dim_product.head()

,ProductID,ProductName,ProductPrice,DepartmentID,DepartmentName,CategoryID,ProductImage
11371,19,Nike Men's Fingertrap Max Training Shoe,124.989998,2,Fitness,2,http://images.acmesports.sports/Nike+Men%27s+F...
175,24,Elevation Training Mask 2.0,79.989998,2,Fitness,2,http://images.acmesports.sports/Elevation+Trai...
5777,35,adidas Brazuca 2014 Official Match Ball,159.990005,2,Fitness,3,http://images.acmesports.sports/adidas+Brazuca...
698,37,adidas Kids' F5 Messi FG Soccer Cleat,34.990002,2,Fitness,3,http://images.acmesports.sports/adidas+Kids%27...
119,44,adidas Men's F10 Messi TRX FG Soccer Cleat,59.990002,2,Fitness,3,http://images.acmesports.sports/adidas+Men%27s...

In [30]:
dim_product.shape

(118, 7)

**LOAD PRODUCT DATA INTO SQL(dimproduct)**

In [31]:
dim_product.to_sql(
    "dimproduct",
    con=engine,
    if_exists="append",
    index=False
)

118

**CREATE DIMENTION TABLE FOR SHIPPING**

In [32]:
dim_shipping = (
    df[
        [
            "ShippingMode",
            "DeliveryStatus",
            "ActualShippingDays",
            "ScheduledShippingDays",
            "LateDeliveryRisk"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_shipping.head()

,ShippingMode,DeliveryStatus,ActualShippingDays,ScheduledShippingDays,LateDeliveryRisk
0,Standard Class,Advance shipping,3,4,0
1,Standard Class,Late delivery,5,4,1
2,Standard Class,Shipping on time,4,4,0
3,Standard Class,Advance shipping,2,4,0
4,Standard Class,Shipping canceled,6,4,0

**CREATE SURROGATE KEY(SHIPPINGKEY)**

In [33]:
dim_shipping["ShippingKey"] = dim_shipping.index + 1

**REORDER SHIPPING DATA**

In [34]:
dim_shipping = dim_shipping[
    [
        "ShippingKey",
        "ShippingMode",
        "DeliveryStatus",
        "ActualShippingDays",
        "ScheduledShippingDays",
        "LateDeliveryRisk"
    ]
]

In [35]:
dim_shipping.shape

(26, 6)

**LOAD SHIPPING DATA INTO SQL(dimshipping)**

In [36]:
dim_shipping.to_sql(
    "dimshipping",
    con=engine,
    if_exists="append",
    index=False
)

26

**CREATE DATAFRAME FOR DATE**

In [37]:
date_dim = pd.DataFrame({
    "FullDate": pd.date_range(
        start=df["OrderDate"].min(),
        end=df["OrderDate"].max()
    )
})

In [38]:
date_dim.head()

    FullDate
0 2015-01-01
1 2015-01-02
2 2015-01-03
3 2015-01-04
4 2015-01-05

**CREATE DATE KEY**

In [39]:
date_dim["DateKey"] = (
    date_dim["FullDate"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

**ADDING REMAINING COLUMNS**

In [40]:
date_dim["Year"] = date_dim["FullDate"].dt.year

date_dim["Quarter"] = date_dim["FullDate"].dt.quarter

date_dim["Month"] = date_dim["FullDate"].dt.month

date_dim["MonthName"] = date_dim["FullDate"].dt.month_name()

date_dim["Day"] = date_dim["FullDate"].dt.day

date_dim["Weekday"] = date_dim["FullDate"].dt.day_name()

date_dim["IsWeekend"] = (
    date_dim["FullDate"].dt.dayofweek >= 5
)

**REORDER CLOUMNS**

In [41]:
date_dim = date_dim[
    [
        "DateKey",
        "FullDate",
        "Year",
        "Quarter",
        "Month",
        "MonthName",
        "Day",
        "Weekday",
        "IsWeekend"
    ]
]

In [42]:
date_dim.head()

,DateKey,FullDate,Year,Quarter,Month,MonthName,Day,Weekday,IsWeekend
0,20150101,2015-01-01,2015,1,1,January,1,Thursday,False
1,20150102,2015-01-02,2015,1,1,January,2,Friday,False
2,20150103,2015-01-03,2015,1,1,January,3,Saturday,True
3,20150104,2015-01-04,2015,1,1,January,4,Sunday,True
4,20150105,2015-01-05,2015,1,1,January,5,Monday,False

**LOAD INTO SQL(datedim)**

In [43]:
date_dim.to_sql(
    "dimdate",
    con=engine,
    if_exists="append",
    index=False
)

1127

**MERGING OUR DATA FRAME WITH SHIPPING TABLE TO GET SHIPPING KEY**

In [44]:
fact_orders = df.merge(
    dim_shipping,
    on=[
        "ShippingMode",
        "DeliveryStatus",
        "ActualShippingDays",
        "ScheduledShippingDays",
        "LateDeliveryRisk"
    ],
    how="left"
)

In [45]:
fact_orders.head()

,OrderType,ActualShippingDays,ScheduledShippingDays,Profit,DeliveryStatus,LateDeliveryRisk,CategoryID,CategoryName,CustomerCity,CustomerCountry,CustomerFirstName,CustomerID,CustomerLastName,CustomerSegment,CustomerState,CustomerStreet,DepartmentID,DepartmentName,Latitude,Longitude,Market,OrderCity,OrderCountry,OrderDate,OrderID,DiscountAmount,DiscountRate,OrderItemID,ProfitRatio,Quantity,GrossSales,NetSales,OrderRegion,OrderState,OrderStatus,ProductID,ProductImage,ProductName,ProductPrice,ShippingDate,ShippingMode,OrderYear,OrderQuarter,OrderMonthNumber,OrderMonth,OrderDay,IsWeekend,ShippingDelay,IsLateDelivery,DeliveryPerformance,ProfitMarginPercent,ProfitCategory,OrderValueCategory,HasDiscount,DiscountCategory,ShippingSpeed,ShippingKey
0,DEBIT,3,4,91.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,2018-01-31 22:56:00,77202,13.110000,0.04,180517,0.29,1,327.75,314.640015,Southeast Asia,Java Occidental,COMPLETE,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-02-03 22:56:00,Standard Class,2018,1,1,January,Wednesday,False,-1,No,Early,27.841342,Low Profit,Premium,Yes,Low,Standard,1
1,TRANSFER,5,4,-249.089996,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,2018-01-13 12:27:00,75939,16.389999,0.05,179254,-0.80,1,327.75,311.359985,South Asia,Rajastán,PENDING,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-18 12:27:00,Standard Class,2018,1,1,January,Saturday,True,1,Yes,Late,-75.999999,Loss,Premium,Yes,Low,Slow,2
2,CASH,4,4,-247.779999,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,2018-01-13 12:06:00,75938,18.030001,0.06,179253,-0.80,1,327.75,309.720001,South Asia,Rajastán,CLOSED,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-17 12:06:00,Standard Class,2018,1,1,January,Saturday,True,0,No,On Time,-75.600305,Loss,Premium,Yes,Low,Standard,3
3,DEBIT,3,4,22.860001,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,2018-01-13 11:45:00,75937,22.940001,0.07,179252,0.08,1,327.75,304.809998,Oceania,Queensland,COMPLETE,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-16 11:45:00,Standard Class,2018,1,1,January,Saturday,True,-1,No,Early,6.974829,Low Profit,Premium,Yes,Low,Standard,1
4,PAYMENT,2,4,134.210007,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,2018-01-13 11:24:00,75936,29.500000,0.09,179251,0.45,1,327.75,298.250000,Oceania,Queensland,PENDING_PAYMENT,1360,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-15 11:24:00,Standard Class,2018,1,1,January,Saturday,True,-2,No,Early,40.948896,Medium Profit,Premium,Yes,Low,Fast,4

In [46]:
fact_orders["ShippingKey"].isnull().sum()

np.int64(0)

**ADDING DATE KEY TO FACT TABLE**

In [47]:
fact_orders["DateKey"] = (
    fact_orders["OrderDate"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

In [48]:
fact_orders[["OrderDate","DateKey"]].head()

            OrderDate   DateKey
0 2018-01-31 22:56:00  20180131
1 2018-01-13 12:27:00  20180113
2 2018-01-13 12:06:00  20180113
3 2018-01-13 11:45:00  20180113
4 2018-01-13 11:24:00  20180113

**REORDER COLUMNS**

In [49]:
fact_orders = fact_orders[
    [
        "OrderItemID",
        "OrderID",
        "CustomerID",
        "ProductID",
        "ShippingKey",
        "DateKey",
        "GrossSales",
        "NetSales",
        "Profit",
        "DiscountAmount",
        "DiscountRate",
        "Quantity",
        "ProfitMarginPercent",
        "ShippingDelay"
    ]
]

In [50]:
fact_orders.head()

,OrderItemID,OrderID,CustomerID,ProductID,ShippingKey,DateKey,GrossSales,NetSales,Profit,DiscountAmount,DiscountRate,Quantity,ProfitMarginPercent,ShippingDelay
0,180517,77202,20755,1360,1,20180131,327.75,314.640015,91.250000,13.110000,0.04,1,27.841342,-1
1,179254,75939,19492,1360,2,20180113,327.75,311.359985,-249.089996,16.389999,0.05,1,-75.999999,1
2,179253,75938,19491,1360,3,20180113,327.75,309.720001,-247.779999,18.030001,0.06,1,-75.600305,0
3,179252,75937,19490,1360,1,20180113,327.75,304.809998,22.860001,22.940001,0.07,1,6.974829,-1
4,179251,75936,19489,1360,4,20180113,327.75,298.250000,134.210007,29.500000,0.09,1,40.948896,-2

In [51]:
fact_orders.shape

(180519, 14)

**CHECKING IF PRIMARY KEY IS UNIQUE OR NOT**

In [52]:
fact_orders["OrderItemID"].is_unique

True

**CHECKING FORIGN KEYS**

In [53]:
fact_orders["CustomerID"].isin(dim_customer["CustomerID"]).all()

np.True_

In [54]:
fact_orders["ProductID"].isin(dim_product["ProductID"]).all()

np.True_

In [55]:
fact_orders["ShippingKey"].isin(dim_shipping["ShippingKey"]).all()

np.True_

In [56]:
fact_orders["DateKey"].isin(date_dim["DateKey"]).all()

np.True_

**LOADING FACT TABLE INTO SQL(factorders)**

In [58]:
fact_orders.to_sql(
    "factorders",
    con=engine,
    if_exists="append",
    index=False
)

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '180517' for key 'factorders.PRIMARY'")
[SQL: INSERT INTO factorders (`OrderItemID`, `OrderID`, `CustomerID`, `ProductID`, `ShippingKey`, `DateKey`, `GrossSales`, `NetSales`, `Profit`, `DiscountAmount`, `DiscountRate`, `Quantity`, `ProfitMarginPercent`, `ShippingDelay`) VALUES (%(OrderItemID)s, %(OrderID)s, %(CustomerID)s, %(ProductID)s, %(ShippingKey)s, %(DateKey)s, %(GrossSales)s, %(NetSales)s, %(Profit)s, %(DiscountAmount)s, %(DiscountRate)s, %(Quantity)s, %(ProfitMarginPercent)s, %(ShippingDelay)s)]
[parameters: [{'OrderItemID': 180517, 'OrderID': 77202, 'CustomerID': 20755, 'ProductID': 1360, 'ShippingKey': 1, 'DateKey': 20180131, 'GrossSales': 327.75, 'NetSales': 314.6400146, 'Profit': 91.25, 'DiscountAmount': 13.10999966, 'DiscountRate': 0.039999999, 'Quantity': 1, 'ProfitMarginPercent': 27.84134248665141, 'ShippingDelay': -1}, {'OrderItemID': 179254, 'OrderID': 75939, 'CustomerID': 19492, 'ProductID': 1360, 'ShippingKey': 2, 'DateKey': 20180113, 'GrossSales': 327.75, 'NetSales': 311.3599854, 'Profit': -249.0899963, 'DiscountAmount': 16.38999939, 'DiscountRate': 0.050000001, 'Quantity': 1, 'ProfitMarginPercent': -75.99999887109077, 'ShippingDelay': 1}, {'OrderItemID': 179253, 'OrderID': 75938, 'CustomerID': 19491, 'ProductID': 1360, 'ShippingKey': 3, 'DateKey': 20180113, 'GrossSales': 327.75, 'NetSales': 309.7200012, 'Profit': -247.7799988, 'DiscountAmount': 18.03000069, 'DiscountRate': 0.059999999, 'Quantity': 1, 'ProfitMarginPercent': -75.60030474446987, 'ShippingDelay': 0}, {'OrderItemID': 179252, 'OrderID': 75937, 'CustomerID': 19490, 'ProductID': 1360, 'ShippingKey': 1, 'DateKey': 20180113, 'GrossSales': 327.75, 'NetSales': 304.8099976, 'Profit': 22.86000061, 'DiscountAmount': 22.94000053, 'DiscountRate': 0.07, 'Quantity': 1, 'ProfitMarginPercent': 6.974828561403509, 'ShippingDelay': -1}, {'OrderItemID': 179251, 'OrderID': 75936, 'CustomerID': 19489, 'ProductID': 1360, 'ShippingKey': 4, 'DateKey': 20180113, 'GrossSales': 327.75, 'NetSales': 298.25, 'Profit': 134.2100067, 'DiscountAmount': 29.5, 'DiscountRate': 0.090000004, 'Quantity': 1, 'ProfitMarginPercent': 40.94889601830664, 'ShippingDelay': -2}, {'OrderItemID': 179250, 'OrderID': 75935, 'CustomerID': 19488, 'ProductID': 1360, 'ShippingKey': 5, 'DateKey': 20180113, 'GrossSales': 327.75, 'NetSales': 294.980011, 'Profit': 18.57999992, 'DiscountAmount': 32.77999878, 'DiscountRate': 0.100000001, 'Quantity': 1, 'ProfitMarginPercent': 5.668954971777269, 'ShippingDelay': 2}, {'OrderItemID': 179249, 'OrderID': 75934, 'CustomerID': 19487, 'ProductID': 1360, 'ShippingKey': 6, 'DateKey': 20180113, 'GrossSales': 327.75, 'NetSales': 288.4200134, 'Profit': 95.18000031, 'DiscountAmount': 39.33000183, 'DiscountRate': 0.119999997, 'Quantity': 1, 'ProfitMarginPercent': 29.04042724942792, 'ShippingDelay': 1}, {'OrderItemID': 179248, 'OrderID': 75933, 'CustomerID': 19486, 'ProductID': 1360, 'ShippingKey': 6, 'DateKey': 20180113, 'GrossSales': 327.75, 'NetSales': 285.1400146, 'Profit': 68.43000031, 'DiscountAmount': 42.61000061, 'DiscountRate': 0.129999995, 'Quantity': 1, 'ProfitMarginPercent': 20.878718630053395, 'ShippingDelay': 1}  ... displaying 10 of 180519 total bound parameter sets ...  {'OrderItemID': 65126, 'OrderID': 26022, 'CustomerID': 2813, 'ProductID': 1004, 'ShippingKey': 1, 'DateKey': 20160115, 'GrossSales': 399.980011, 'NetSales': 387.980011, 'Profit': 186.2299957, 'DiscountAmount': 12.0, 'DiscountRate': 0.029999999, 'Quantity': 1, 'ProfitMarginPercent': 46.55982563588659, 'ShippingDelay': -1}, {'OrderItemID': 65113, 'OrderID': 26018, 'CustomerID': 7547, 'ProductID': 1004, 'ShippingKey': 3, 'DateKey': 20160115, 'GrossSales': 399.980011, 'NetSales': 383.980011, 'Profit': 168.9499969, 'DiscountAmount': 16.0, 'DiscountRate': 0.039999999, 'Quantity': 1, 'ProfitMarginPercent': 42.239610043912926, 'ShippingDelay': 0}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)